name: Build Docs

on:
  push:
    branches:
      - master
      - main
      - dev

  pull_request:
    branches:
      - master
      - main
      - dev

jobs:

  build_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: Update Pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        # note that we also install the sphinx template, here. If you change the template (see `docs/source/conf.py`)
        run: |
          pip install sphinx pydata-sphinx-theme setuptools-scm

      - name: Sphinx build
        run: |
          sphinx-apidoc -o docs/source/_autogen .
          sphinx-build -M html docs/source docs/build

      - name: Push to branch
        run: |
          git diff --quiet || git stash --quiet
          git checkout -B "gh-docs-${{steps.extract_branch.outputs.branch}}"
          
          if git stash list | grep -q "stash@{0}"; then
            git stash pop --quiet || { echo "Unexpected conflict during stash."; exit 1; }
          fi   
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "docbot@users.noreply.github.com"
          
          git add .
          git add -f docs/build/html
          
          git diff-index --quiet HEAD || git commit -m "docs: auto-generated documentation update [skip ci]"
          
          git push --force origin "gh-docs-${{steps.extract_branch.outputs.branch}}"
